# Service name
spring.application.name=rhythmix-user-service

# PostgreSQL connection string
ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=rhythmix;Username=rhythmix;Password=rhythmix
